---
- name: Listen for events on a webhook
  hosts: all

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: "{{ source_port }}"

  rules:
    - name: Say Hello
      condition: event.payload.message == 'x-hello'
      action:
        run_job_template:
          name: 'hello'
          organization: Test
